### ISSUE TITLE
Request name is not properly displayed

### ISSUE THREAD

**Issue by simmosoonsein** [ervirendersingh/newman-reporter-allure#2]
I have a request defined in Postman: "dummyRequest"
this dummyRequest is calling another request with setNextRequest("dummyRequest2")

After executing tests in Newman and checking the report I see following.
Report does not display me request name, but iterationNo_setNextRequest_4 instead:
![image](https://user-images.githubusercontent.com/47790085/74023206-c4e61300-49a7-11ea-8cca-88146867b81a.png)
![image](https://user-images.githubusercontent.com/47790085/74023321-1098bc80-49a8-11ea-8d99-df16a54cb92b.png)

I would expect to see the initial request name instead.

**Comment by Ulasko** [comment]
Comment that line ".replace(/[\u0100-\uffff]/g, (c) => `|0x${c.charCodeAt(0).toString(16).padStart(4, "0")}`);"  line 369 in AppData\Roaming\npm\node_modules\newman-reporter-allure\index.js

**Comment by ervirendersingh** [comment]
Issue is fixed. Now, the exact name of the request is displayed.
