### ISSUE TITLE
 the json file schema unloaded from the postman does not match.

### ISSUE THREAD

**Issue by svmyhome** [ervirendersingh/newman-reporter-allure#4]
I export data from postman. My schema does not match the schema of the json file you showed. How do you upload in your format?

**Comment by ervirendersingh** [comment]
not sure if this is the answer to your question but if you are talking about the sample collection then my export is "Collection v2.1 (recommended)"

![postman_export_coll](https://user-images.githubusercontent.com/36705992/81258169-6bf64b80-9078-11ea-8337-c0574a28bf3b.jpg)
