### ISSUE TITLE
Can we have allure report to exclude response body

### ISSUE THREAD

**Issue by sachin-s-joshi** [ervirendersingh/newman-reporter-allure#9]
I have API running in collection and reports generated in allure has response which is very big in size.
Would it be possible to have option such that we can have report without response body?
<img width="1572" alt="Screenshot 2020-07-24 at 1 50 37 PM" src="https://user-images.githubusercontent.com/18211007/88373027-b3a58d00-cdb4-11ea-900c-63b1a0a63d29.png">

**Comment by SJ1591** [comment]
Any updates on this @ervirendersingh
